version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-grants-slurry-web:
    build:
      context: .
      target: development
    depends_on:
      - redis
    image: ffc-grants-slurry-web-development
    environment:
      NODE_ENV: development
    ports:
      - "3600:3600"
      - "9235:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json

  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6383:6379"

volumes:
  redis_data:
